name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  # test:
  #   name: Test
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: â¬‡ï¸ Checkout Repo
  #       uses: actions/checkout@v2
  #     - name: â” Setup Node.js
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: 15
  #     - name: ğŸ“¥ Install dependencies
  #       run: yarn install
  #     - name: ğŸ— Build package
  #       run: yarn build
  #     - name: ğŸ§ª Test package
  #       run: yarn test
  release:
    name: Release
    # needs: test
    # if: ${{ github.ref == 'refs/heads/master' && github.event_name != 'pull_request'}}
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ›‘ Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: â¬‡ï¸ Checkout Repo
        uses: actions/checkout@v2
      - name: ğŸš€ Release
        uses: cycjimmy/semantic-release-action@v2
        id: semantic
        dry_run: true
        with:
          semantic_version: 17.4.3
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
            conventional-changelog-conventionalcommits
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}